### ISSUE TITLE
Metodi privati

### ISSUE THREAD

**Issue by supix** [Digre001/Progetto_KNN#1]
Potrebbe aver senso utilizzare, ove opportuno, la convenzione Python per rendere privati i metodi che non dovrebbero essere accessibili all'esterno di una classe? (come per esempio quello indicato di seguito).

https://github.com/Digre001/Progetto_KNN/blob/5e590673665bb5a51fde4026de7533bd989024f9/M_Development.py#L53

**Comment by Digre001** [comment]
La ringraziamo per il feedback,

Abbiamo modificato il metodo distanza_euclidea in un metodo privato, oltre a questo abbiamo fatto lo stesso per il metodo split della classe DataSplitter appartenete al file L&F.py
