### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by supix** [Digre001/Progetto_KNN#2]
La naming convention del Python suggerisce di usare nomi minuscoli per i metodi, separando le parole con un trattino (vedere [qui](https://peps.python.org/pep-0008/#method-names-and-instance-variables)). Un metodo che inizia con una lettera maiuscola può essere inavvertitamente scambiato per il nome di una classe (vedere [qui](https://peps.python.org/pep-0008/#class-names)).

https://github.com/Digre001/Progetto_KNN/blob/5e590673665bb5a51fde4026de7533bd989024f9/selezione_input.py#L7

**Comment by Digre001** [comment]
Abbiamo apportato le modifiche nel main, andando ad aumentare cosi la leggibilità del codice 
grazie per il consiglio

**Comment by supix** [comment]
Ok. Resta solo da correggere questo che sembra un piccolo errore di battitura.

https://github.com/Digre001/Progetto_KNN/blob/0121348267268dca39c29302e66fc011a3329bb8/selezione_input.py#L7
